#!/usr/bin/env node

const generate = require('../commands/generate');
const start = require('../commands/start');

const argv = require('minimist')(process.argv.slice(2));

const command = argv._[0];

switch (command) {
    case 'generate': {
        const { url } = argv;
        return generate(url);
    }

    case 'start': {
        return start();
    }

    default: {
        console.error('Not a valid command');
    }
}
